CREATE TABLE tb_readers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    age INT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_books (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    genre VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL UNIQUE,
    reader_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_books_readers FOREIGN KEY (reader_id) REFERENCES tb_readers(id)
);